Repository lablup/backend.ai-webserver, pull requests merged in 2020-10, with the labels that each got.

#21 fix: specify no-store only to disable cache for static files
  changes/21.fix
  src/ai/backend/console/server.py
Labels: bot:chronographer:provided, bug

#22 feat: add option to enable/disable open port to public checkbox
  changes/22.feature
  console-server.sample.conf
  src/ai/backend/console/server.py
Labels: bot:chronographer:provided, enhancement

#23 setup: Update dependencies (aiohttp 3.7.1 and others)
  setup.cfg
Labels: enhancement

#24 fix: Apply client-py Request arg refactoring
  src/ai/backend/console/proxy.py
Labels: bug

#25 setup: Update dependencies (aiohttp 3.7.2)
  changes/25.fix
  setup.cfg
Labels: bot:chronographer:provided, enhancement

#26 ci: Add deploy and test workflows and activate submodules option in checkout step
  .github/workflows/deploy-pypi.yml
  .github/workflows/lint-towncrier.yml
  .github/workflows/test-pytest.yml
  .travis.yml
  changes/26.misc
Labels: enhancement
